# Generated by Django 4.1.2 on 2022-11-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("age", models.IntegerField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
